# Generated by Django 4.2.30 on 2026-04-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('email_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
