# Generated by Django 4.2.30 on 2026-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_actiontracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontracker',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
