# Generated by Django 4.2.30 on 2026-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_emaillog_delete_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
