# Generated by Django 4.2.30 on 2026-04-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_client_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='duedate',
        ),
    ]
