# Generated by Django 4.2.30 on 2026-04-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_notification_is_read_emaillog_ticket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageTemplate',
            new_name='EmailTemplate',
        ),
    ]
