# Generated by Django 4.2.30 on 2026-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_rename_messagetemplate_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontracker',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='actiontracker',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actiontracker',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
