# Generated by Django 4.2.30 on 2026-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoiceitem_actiontracker_confirmation_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('invoice_generated', 'Invoice Generated'), ('due_tomorrow', '1 Day Before Due'), ('due_today', 'Due Date'), ('suspension', 'Suspension'), ('confirmation', 'Confirmation'), ('queue', 'Queue'), ('termination', 'Termination')], max_length=50, unique=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type'],
            },
        ),
    ]
