# Generated by Django 4.2.30 on 2026-04-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_messagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='template_type',
            field=models.CharField(choices=[('invoice_generated', 'Invoice Generated'), ('due_tomorrow', '1 Day Before Due'), ('due_today', 'Due Date'), ('suspension', 'Suspension'), ('confirmation', 'Confirmation'), ('queue', 'Queue'), ('termination', 'Termination')], max_length=50),
        ),
    ]
